format: 0.4.0
primaryJobName: ipfs_deploy
jobs:
  ipfs_deploy:
    steps:
      - name: ipfs_deploy
        package: ipfs
        uri: fs/./build
        config:
          gatewayUri: https://ipfs.wrappers.io
