#!/usr/bin/env bash
set -e

PWR_DIR=${PWR_DIR-"$HOME/.pwr"}
PWR_BIN_DIR="$PWR_DIR/bin"

BINS=(pwr)

export RUSTFLAGS="-C target-cpu=native"

main() {
  need_cmd git
  need_cmd curl

  while [[ $1 ]]; do
    case $1 in
      --)               shift; break;;

      -r|--repo)        shift; PWRUP_REPO=$1;;
      -b|--branch)      shift; PWRUP_BRANCH=$1;;
      -v|--version)     shift; PWRUP_VERSION=$1;;
      -p|--path)        shift; PWRUP_LOCAL_REPO=$1;;
      -P|--pr)          shift; PWRUP_PR=$1;;
      -C|--commit)      shift; PWRUP_COMMIT=$1;;
      -h|--help)
        usage
        exit 0
        ;;
      *)
        warn "unknown option: $1"
        usage
        exit 1
    esac; shift
  done

  # Print the banner after successfully parsing args
  banner

  if [ -n "$PWRUP_PR" ]; then
    if [ -z "$PWRUP_BRANCH" ]; then
      PWRUP_BRANCH="refs/pull/$PWRUP_PR/head"
    else
      err "can't use --pr and --branch at the same time"
    fi
  fi

  # Installs pwr from a local repository if --path parameter is provided
  if [[ -n "$PWRUP_LOCAL_REPO" ]]; then
    need_cmd cargo

    # Ignore branches/versions as we do not want to modify local git state
    if [ -n "$PWRUP_REPO" ] || [ -n "$PWRUP_BRANCH" ] || [ -n "$PWRUP_VERSION" ]; then
      warn "--branch, --version, and --repo arguments are ignored during local install"
    fi

    # Enter local repo and build
    say "installing from $PWRUP_LOCAL_REPO"
    cd "$PWRUP_LOCAL_REPO"
    ensure cargo build --release # need 4 speed

    for bin in "${BINS[@]}"; do
      # Remove prior installations if they exist
      rm -f "$PWR_BIN_DIR/$bin"
      # Symlink from local repo binaries to bin dir
      ensure ln -s "$PWD/target/release/$bin" "$PWR_BIN_DIR/$bin"
    done

    say "done"
    exit 0
  fi

  PWRUP_REPO=${PWRUP_REPO-polywrap/pwr}

  # Install by downloading binaries
  if [[ "$PWRUP_REPO" == "polywrap/pwr" && -z "$PWRUP_BRANCH" && -z "$PWRUP_COMMIT" ]]; then
    PWRUP_VERSION=${PWRUP_VERSION-nightly}
    PWRUP_TAG=$PWRUP_VERSION

    # Normalize versions (handle channels, versions without v prefix
    if [[ "$PWRUP_VERSION" == "nightly" ]]; then
      # Locate real nightly tag
      SHA=$(ensure curl -sSf "https://api.github.com/repos/$PWRUP_REPO/git/refs/tags/nightly" \
        | grep -Eo '"sha"[^,]*' \
        | grep -Eo '[^:]*$' \
        | tr -d '"' \
        | tr -d ' ' \
        | cut -d ':' -f2 )
      PWRUP_TAG="nightly-${SHA}"
    elif [[ "$PWRUP_VERSION" == nightly* ]]; then
      PWRUP_VERSION="nightly"
    elif [[ "$PWRUP_VERSION" == [[:digit:]]* ]]; then
      # Add v prefix
      PWRUP_VERSION="v${PWRUP_VERSION}"
      PWRUP_TAG="${PWRUP_VERSION}"
    fi

    say "installing pwr (version ${PWRUP_VERSION}, tag ${PWRUP_TAG})"

    PLATFORM="$(uname -s)"
    EXT="tar.gz"
    case $PLATFORM in
      Linux)
        PLATFORM="linux"
        ;;
      Darwin)
        PLATFORM="darwin"
        ;;
      MINGW*)
        EXT="zip"
        PLATFORM="win32"
        ;;
      *)
        err "unsupported platform: $PLATFORM"
        ;;
    esac

    ARCHITECTURE="$(uname -m)"
    if [ "${ARCHITECTURE}" = "x86_64" ]; then
      # Redirect stderr to /dev/null to avoid printing errors if non Rosetta.
      if [ "$(sysctl -n sysctl.proc_translated 2>/dev/null)" = "1" ]; then
        ARCHITECTURE="arm64" # Rosetta.
      else
        ARCHITECTURE="amd64" # Intel.
      fi
    elif [ "${ARCHITECTURE}" = "arm64" ] ||[ "${ARCHITECTURE}" = "aarch64" ] ; then
      ARCHITECTURE="arm64" # Arm.
    else
      ARCHITECTURE="amd64" # Amd.
    fi

    # Compute the URL of the release tarball in the pwr repository.
    RELEASE_URL="https://github.com/${PWRUP_REPO}/releases/download/${PWRUP_TAG}/"
    BIN_ARCHIVE_URL="${RELEASE_URL}pwr_${PWRUP_VERSION}_${PLATFORM}_${ARCHITECTURE}.$EXT"
    say $BIN_ARCHIVE_URL
    # Download and extract the binaries archive
    say "downloading the latest pwr binary"
    if [ "$PLATFORM" = "win32" ]; then
      tmp="$(mktemp -d 2>/dev/null || echo ".")/pwr.zip"
      ensure download "$BIN_ARCHIVE_URL" "$tmp"
      ensure unzip "$tmp" -d "$PWR_BIN_DIR"
      rm -f "$tmp"
    else
      ensure download "$BIN_ARCHIVE_URL" | ensure tar -xzC "$PWR_BIN_DIR"
    fi

    for bin in "${BINS[@]}"; do
      bin_path="$PWR_BIN_DIR/$bin"

      # Print installed msg
      say "installed - $(ensure "$bin_path" version)"

      # Check if the default path of the binary is not in PWR_BIN_DIR
      which_path="$(which "$bin")"
      if [ "$which_path" != "$bin_path" ]; then
        warn ""
        cat 1>&2 <<EOF
There are multiple binaries with the name '$bin' present in your 'PATH'.
This may be the result of installing '$bin' using another method,
like Cargo or other package managers.
You may need to run 'rm $which_path' or move '$PWR_BIN_DIR'
in your 'PATH' to allow the newly installed version to take precedence!

EOF
      fi
    done

    say "done!"

  # Install by cloning the repo with the provided branch/tag
  else
    need_cmd cargo
    PWRUP_BRANCH=${PWRUP_BRANCH-master}
    REPO_PATH="$PWR_DIR/$PWRUP_REPO"

    # If repo path does not exist, grab the author from the repo, make a directory in .pwr, cd to it and clone.
    if [ ! -d "$REPO_PATH" ]; then
      AUTHOR="$(echo "$PWRUP_REPO" | cut -d'/' -f1 -)"
      ensure mkdir -p "$PWR_DIR/$AUTHOR"
      cd "$PWR_DIR/$AUTHOR"
      ensure git clone "https://github.com/$PWRUP_REPO"
    fi

    # Force checkout, discarding any local changes
    cd "$REPO_PATH"
    ensure git fetch origin "${PWRUP_BRANCH}:remotes/origin/${PWRUP_BRANCH}"
    ensure git checkout "origin/${PWRUP_BRANCH}"

    # If set, checkout specific commit from branch
    if [ -n "$PWRUP_COMMIT" ]; then
      say "installing at commit $PWRUP_COMMIT"
      ensure git checkout "$PWRUP_COMMIT"
    fi

    # Build the repo and install the binaries locally to the .pwr bin directory.
    # --root appends /bin to the directory it is given, so we pass PWR_DIR.
    ensure cargo install --path ./rust/pwr --bins --locked --force --root "$PWR_DIR"

    say "done"
  fi
}

usage() {
  cat 1>&2 <<EOF
The installer for the PWR CLI.

Allows changing the version of the PWR CLI.

USAGE:
    pwrup <OPTIONS>

OPTIONS:
    -h, --help      Print help information
    -v, --version   Install a specific version
    -b, --branch    Install a specific branch
    -P, --pr        Install a specific Pull Request
    -C, --commit    Install a specific commit
    -r, --repo      Install from a remote GitHub repo (uses default branch if no other options are set)
    -p, --path      Install a local repository
EOF
}

say() {
  printf "pwrup: %s\n" "$1"
}

warn() {
  say "warning: ${1}" >&2
}

err() {
  say "$1" >&2
  exit 1
}

need_cmd() {
  if ! check_cmd "$1"; then
    err "need '$1' (command not found)"
  fi
}

check_cmd() {
  command -v "$1" &>/dev/null
}

# Run a command that should never fail. If the command fails execution
# will immediately terminate with an error showing the failing
# command.
ensure() {
  if ! "$@"; then err "command failed: $*"; fi
}

# Downloads $1 into $2 or stdout
download() {
  if [ "$2" ]; then
    # output into $2
    if check_cmd curl; then
      curl -#o "$2" -L "$1"
    else
      wget --show-progress -qO "$2" "$1"
    fi
  else
    # output to stdout
    if check_cmd curl; then
      curl -#L "$1"
    else
      wget --show-progress -qO- "$1"
    fi
  fi
}

banner() {
  printf '
========================================================================

██████╗ ██╗    ██╗██████╗ 
██╔══██╗██║    ██║██╔══██╗
██████╔╝██║ █╗ ██║██████╔╝
██╔═══╝ ██║███╗██║██╔══██╗
██║     ╚███╔███╔╝██║  ██║
╚═╝      ╚══╝╚══╝ ╚═╝  ╚═╝

========================================================================
Repository: https://github.com/polywrap/pwr/
========================================================================
'
}


main "$@" || exit 1