[package]
name = "pwr"
version = "0.1.4"

edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
polywrap_client.workspace = true
polywrap_client_builder.workspace = true
polywrap_client_default_config.workspace = true
wrap_manifest_schemas.workspace = true
polywrap_msgpack.workspace = true
polywrap_fs_plugin.workspace = true
polywrap_http_plugin.workspace = true
rmpv.workspace = true
serde.workspace = true
serde_bytes.workspace = true
serde_json.workspace = true
rmp-serde.workspace = true
wrap_utils.workspace = true
wrap_utils_wasm.workspace = true
script_wrap_utils.workspace = true
tokio.workspace = true
script_wrap_utils_wasm.workspace = true
easy_error_string.workspace = true

dirs = "5.0.0"
clap = { version = "4.3.4", features = ["cargo"] }
tokio-tar = "0.3"
tokio-util = "0.6"
futures = "0.3"
colored = "2.0.0"
notify = "6.0.1"
notify-debouncer-mini = "0.3.0"
openssl = { version = "0.10.55", features = ["vendored"] }
