[package]
name = "easy_error_string"
description = "Simplified error handling for the lazy developer"
version = "0.1.0"

edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
