[package]
name = "module"
version = "0.1.0"
description = "Manager for script wraps"

edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
polywrap-wasm-rs.workspace = true
serde.workspace = true
serde_json.workspace = true
base64.workspace = true
script_wrap_utils_wasm.workspace = true
wrap_utils_wasm.workspace = true
easy_error_string.workspace = true
serde_bytes.workspace = true
polywrap_msgpack_serde.workspace = true

[lib]
crate-type = ["cdylib"]

[profile.release]
opt-level = 's'
lto = true
panic = 'abort'
