[package]
name = "script_wrap_utils_wasm"
version = "0.1.0"

edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
rmpv.workspace = true
serde.workspace = true
serde_bytes.workspace = true
serde_json.workspace = true
rmp-serde.workspace = true
wrap_utils_wasm.workspace = true
thiserror.workspace = true