[package]
name = "multipart"
version = "0.1.0"
description = "Wrap that provides support for POST multipart/form-data requests"

edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
polywrap-wasm-rs.workspace = true
serde.workspace = true
multipart = { version = "0.18.0", default-features = false, features = ["server"] }
getrandom = { version = "=0.2.9", features = ["custom"] }
serde_bytes.workspace = true
polywrap_msgpack_serde.workspace = true

[lib]
crate-type = ["cdylib"]

[profile.release]
opt-level = 's'
lto = true
panic = 'abort'
